server {
    listen 80;

    location /create-order {
        proxy_pass http://order-service:3000/create-order;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Bloquea el acceso directo a otros endpoints
    location / {
        return 403;
    }
}
